### ISSUE TITLE
Get Song By ID?

### ISSUE THREAD

**Issue by abhishrant** [koehlma/pygrooveshark#19]
Hello all Devs,

How can I get a Song object by Song ID which I got from search?

Thank You

**Comment by koehlma** [comment]
Hi there,

the `Client.search` method should return Song objects. If you want to use an ID from an other source beside this implementation this isn't currently possible although there should be a "GetSongById" API method so it could easily be implemented.

But for now I have some other priorities so I am not actively maintaining this anymore. Because of that there are also some other issues because it uses an outdated api. Feel free to send pull-requests anyway.

**Comment by abhishrant** [comment]
Okay if it can be easily implemented then let me look into it. :D

Thank You,
