### ISSUE TITLE
Add support for broadcast

### ISSUE THREAD

**Issue by camilonova** [koehlma/pygrooveshark#24]
I have tried to do it by myself, but I couldn't find a way to do it.

**Comment by camilonova** [comment]
@koehlma any comment about this one?

**Comment by koehlma** [comment]
I did some reverse engineering, so I think it could be done by implementing "getBroadcast" and "getTopBroadcastsCombinedEx" API methods. The responses contain the current song as well as the position you need to seek to and the next song(s). But for now I do not have enough time to implement it although I would be really glad to see this in Mopidy.

**Comment by camilonova** [comment]
@koehlma do you think you will have some available time soon (couple months)?

If not, can you sketch some basic steps so I can try to do it on my own?

**Comment by koehlma** [comment]
I am not sure because I am very busy and if I do so I would like to do a complete makeover because the other parts of the API are outdated.

You need to reverse engineer the missing parts of the unofficial API and then reimplement them in Python using the `Connection`-class which provides some low level API abstraction. This could be done by using [FireBug](https://addons.mozilla.org/de/firefox/addon/firebug/). As I mentioned before a problem might be that the whole API is outdated, so other parts need to be changed as well to make it work.

**Comment by koehlma** [comment]
I forgot to mention that there is a tool to help you with reverse engineer the API. Have a look at https://github.com/koehlma/pygrooveshark/blob/develop/utils/grooveshark_analyzer.py it's a proxy which shows you the API calls.
